Databases(C, C#)/DB_lab2/GameStop (Waresoft)/Models/Developers.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Waresoft
{
    public partial class Developer
    {
        private const string ERR_REQ = "Поле необхідно заповнити";

        public Developer()
        {
            Software = new HashSet<Software>();
        }

        public int Id { get; set; }

        [Display(Name = "Країна")]
        public int CountryId { get; set; }

        [Required(ErrorMessage = ERR_REQ)]
        [StringLength(50)]
        [Display(Name = "Ім\'я/назва")]
        public string Name { get; set; }

        [Display(Name = "Країна")]
        public virtual Country Country { get; set; }
        public virtual ICollection<Software> Software { get; set; }
    }
}

Databases(C, C#)/DB_lab2/GameStop (Waresoft)/Controllers/DevelopersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Waresoft;

namespace Waresoft.Controllers
{
    public class DevelopersController : Controller
    {
        private const string ERR_DEV_EXISTS = "Введений розробник вже доданий";
        private readonly WaresoftContext _context;

        public DevelopersController(WaresoftContext context)
        {
            _context = context;
        }

        // GET: Developers
        public async Task<IActionResult> Index()
        {
            return View(await _context.Developers.Include("Country").ToListAsync());
        }

        // GET: Developers/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var software = await _context.Software.Where(s => s.DeveloperId == id).Include("Comments").ToListAsync();
            ViewBag.Developer = _context.Developers.Find(id).Name;
            return View();
        }

        // GET: Developers/Create
        public IActionResult Create()
        {
            ViewBag.CountryList = new SelectList(_context.Countries.ToList(), "Id", "Name");
            return View();
        }

        // POST: Developers/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Developer developer)
        {
            bool duplicate = await _context.Developers.AnyAsync(d => d.Name.Equals(developer.Name));

            if (duplicate)
            {
                ModelState.AddModelError("Name", ERR_DEV_EXISTS);
            }

            if (ModelState.IsValid)
            {
                _context.Add(developer);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            ViewBag.CountryList = new SelectList(_context.Countries.ToList(), "Id", "Name");
            return View(developer);
        }

        // GET: Developers/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            var developers = await _context.Developers.FindAsync(id);
            ViewBag.CountryList = new SelectList(_context.Countries.ToList(), "Id", "Name");
            return View(developers);
        }

        // POST: Developers/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Developer developer)
        {
            bool duplicate = await _context.Developers.AnyAsync(d => d.Name.Equals(developer.Name) && d.CountryId == developer.CountryId && d.Id != developer.Id);

            if (duplicate)
            {
                ModelState.AddModelError("Name", ERR_DEV_EXISTS);
            }

            if (ModelState.IsValid)
            {
                _context.Update(developer);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            ViewBag.CountryList = new SelectList(_context.Countries.ToList(), "Id", "Name");
            return View(developer);
        }

        // POST: Developers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var developers = await _context.Developers.FindAsync(id);
            _context.Developers.Remove(developers);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

Databases(C, C#)/DB_lab2/GameStop (Waresoft)/Controllers/SoftwareController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Waresoft;

namespace Waresoft.Controllers
{
    public class SoftwareController : Controller
    {
        private const string ERR_SOFT_EXISTS = "Такий продукт вже доданий";
        private readonly WaresoftContext _context;

        public SoftwareController(WaresoftContext context)
        {
            _context = context;
        }

        // GET: Software
        public async Task<IActionResult> Index(int id, bool purchased)
        {
            List<Software> software;
            ViewBag.DevId = id;
            
            if (purchased)
            {
                ViewBag.Purchased = 1;
            }

            if (id == 0)
            {
                software = await _context.Software.Include(s => s.Developer).ToListAsync();
            }
            else
            {
                ViewBag.Developer = _context.Developers.Find(id).Name;
                software = await _context.Software.Where(s => s.DeveloperId == id).Include(s => s.Developer).ToListAsync();
            }

            return View(software);
        }

        // GET: Software/Create
        public IActionResult Create(int devId)
        {
            ViewBag.DevId = devId;
            if (devId != 0)
            {
                ViewBag.Developer = _context.Developers.Find(devId).Name;
            }
            ViewBag.DeveloperList = devId == 0 ?
            new SelectList(_context.Developers, "Id", "Name") :
            new SelectList(new List<Developer>() { _context.Developers.Find(devId) }, "Id", "Name");
            return View();
        }

        // POST: Software/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Software software)
        {
            ViewBag.DevId = software.DeveloperId;
            ViewBag.Developer = _context.Developers.Find(software.DeveloperId).Name;

            bool duplicate = _context.Software.Any(s => s.DeveloperId == software.DeveloperId && s.Name.Equals(software.Name));

            if (duplicate)
            {
                ModelState.AddModelError("Name", ERR_SOFT_EXISTS);
            }

            if (ModelState.IsValid)
            {
                _context.Add(software);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", new { id = software.DeveloperId });
            }

            ViewBag.DeveloperList = new SelectList(_context.Developers, "Id", "Name", software.DeveloperId);
            return View(software);
        }

        // GET: Software/Edit/5
        public async Task<IActionResult> Edit(int id, int devId)
        {
            var software = await _context.Software.FindAsync(id);
            ViewBag.DevId = devId;
            ViewBag.DeveloperList = new SelectList(_context.Developers, "Id", "Name", software.DeveloperId);
            return View(software);
        }

        // POST: Software/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Software software, int devId)
        {
            ViewBag.DevId = devId;
            bool duplicate = _context.Software.Any(s => s.Id != software.Id && s.DeveloperId == software.DeveloperId && s.Name.Equals(software.Name));

            if (duplicate)
            {
                ModelState.AddModelError("Name", ERR_SOFT_EXISTS);
            }

            if (ModelState.IsValid)
            {
                _context.Update(software);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index), new { id = devId });
            }

            ViewBag.DeveloperList = new SelectList(_context.Developers, "Id", "Name", software.DeveloperId);
            return View(software);
        }

        // POST: Software/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var software = await _context.Software.FindAsync(id);
            _context.Software.Remove(software);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

Databases(C, C#)/DB_lab2/GameStop (Waresoft)/Views/Developers/Create.cshtml
@model Waresoft.Developer

@{
    ViewData["Title"] = "Додати розробника";
}

<h4>Додати розробника</h4>
<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CountryId" class="control-label"></label>
                <select asp-for="CountryId" class="form-control" asp-items="@ViewBag.CountryList"></select>
            </div>
            <table>
                <tr>
                    <td>
                        <input type="submit" value="Додати" class="btn btn-outline-dark" />
                    </td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>
                        <button type="button" class="btn btn-outline-dark" data-toggle="modal"  data-target="#confirm">
                            Назад до списку
                        </button>
                    </td>
                </tr>
            </table>
        </form>
    </div>
</div>

<form method="get" asp-action="Index">
    <div class="modal fade" id="confirm" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Попередження</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body delete-modal-body">
                    Ви впевнені, що хочете повернутися до списку? Незбережені дані будуть втрачені.
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-outline-dark">Так</button>
                    <button type="button" class="btn btn-outline-dark" data-dismiss="modal">Ні</button>
                </div>
            </div>
        </div>
    </div>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Databases(C, C#)/DB_lab2/GameStop (Waresoft)/Views/Developers/Details.cshtml
@model IEnumerable<Software>

@{
    ViewData["Title"] = ViewBag.Developer;
}

<h1>@ViewBag.Developer</h1>

@foreach (var item in Model)
{
    <div class="row">
        <div class="col-md-4">
            <p><b>Назва:</b> @item.Name</p>
            <p><b>Вартість:</b> @item.Price</p>
            <p><b>Опис</b></p>
            <p>@item.Description</p>
            <p><b>Системні вимоги</b></p>
            <p>@item.Requirements</p>
        </div>
    </div>
}
<form method="get" asp-action="Index">
    <input type="submit" class="btn btn-outline-dark" value="Назад до списку" />
</form>

Databases(C, C#)/DB_lab2/GameStop (Waresoft)/Views/Developers/Edit.cshtml
@model Waresoft.Developer

@{
    ViewData["Title"] = "Редагування";
}

<h4>Редагувати дані розробника</h4>
<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CountryId" class="control-label"></label>
                <select asp-for="CountryId" class="form-control" asp-items="@ViewBag.CountryList"></select>
            </div>

            <div class="modal fade" id="confirm" tabindex="-1" role="dialog" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title">Попередження</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body delete-modal-body">
                            Ви впевнені, що хочете зберегти внесені зміни?
                        </div>
                        <div class="modal-footer">
                            <button type="submit" class="btn btn-outline-dark" onclick="yes()">Так</button>
                            <button type="button" class="btn btn-outline-dark" data-dismiss="modal">Ні</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

<table>
    <tr>
        <td>
            <button type="button" class="btn btn-outline-dark" data-toggle="modal" data-target="#confirm">
                Зберегти
            </button>
        </td>
        <td></td>
        <td></td>
        <td></td>
        <td>
            <button type="button" class="btn btn-outline-dark" data-toggle="modal" data-target="#confirmBack">
                Назад до списку
            </button>
        </td>
    </tr>
</table>

<form method="get" asp-action="Index">
    <div class="modal fade" id="confirmBack" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Попередження</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body delete-modal-body">
                    Ви впевнені, що хочете повернутися до списку? Незбережені зміни будуть втрачені.
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-outline-dark">Так</button>
                    <button type="button" class="btn btn-outline-dark" data-dismiss="modal">Ні</button>
                </div>
            </div>
        </div>
    </div>
</form>

@section Scripts
{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script>
        function yes() {
            $("#confirm").modal('hide');
        }
    </script>
}

Databases(C, C#)/DB_lab2/GameStop (Waresoft)/Views/Developers/Index.cshtml
@model IEnumerable<Waresoft.Developer>

@{
    ViewData["Title"] = "Розробники";
}

<h1>Розробники</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Country)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            var targetId = "#modal" + item.Id;
            var modalId = "modal" + item.Id;
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Country.Name)
                </td>
                <td>
                    <div class="btn-toolbar">
                        <form method="get" asp-controller="Software" asp-action="Index" asp-route-id="@item.Id">
                            <input type="submit" class="btn btn-outline-dark mr-2" value="Список продуктів" />
                        </form>
                        <form method="get" asp-action="Edit" asp-route-id="@item.Id">
                            <input type="submit" class="btn btn-outline-dark mr-2" value="Редагувати" />
                        </form>
                        <button type="button" class="btn btn-outline-dark mr-2" data-toggle="modal" data-target="@targetId">
                            Видалити
                        </button>
                    </div>

                    <div class="modal fade" id="@modalId" tabindex="-1" role="dialog" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title">Попередження</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body delete-modal-body">
                                    Ви впевнені, що хочете видалити цього розробника?
                                </div>
                                <div class="modal-footer">
                                    <form asp-action="Delete" asp-route-id="@item.Id">
                                        <button type="submit" class="btn btn-outline-dark">Так</button>
                                        <button type="button" class="btn btn-outline-dark" data-dismiss="modal">Ні</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>

<table>
    <tr>
        <td>
            <form method="get" asp-action="Create">
                <input type="submit" class="btn btn-outline-dark" value="Додати нового" />
            </form>
        </td>
        <td></td>
        <td></td>
        <td></td>
        <td>
            <form method="get" asp-controller="Home" asp-action="Index">
                <input type="submit" class="btn btn-outline-dark" value="На головну" />
            </form>
        </td>
    </tr>
</table>