Databases(C, C#)/DB_lab2/GameStop (Waresoft)/Models/Software.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Waresoft
{
    public partial class Software
    {
        private const string ERR_REQ = "Поле необхідно заповнити";

        public Software()
        {
            Purchases = new HashSet<Purchase>();
        }

        public int Id { get; set; }

        [Display(Name = "Розробник")]
        public int DeveloperId { get; set; }
        
        [Required(ErrorMessage = ERR_REQ)]
        [StringLength(50)]
        [Display(Name = "Назва")]
        public string Name { get; set; }

        [Required(ErrorMessage = ERR_REQ)]
        [RegularExpression(@"^[0-9]+(\.[0-9]{1,2})?$", ErrorMessage = "Введіть коректну вартість")]
        [Display(Name = "Вартість")]
        public decimal Price { get; set; }

        [Required(ErrorMessage = ERR_REQ)]
        [Display(Name = "Опис")]
        public string Description { get; set; }

        [Required(ErrorMessage = ERR_REQ)]
        [Display(Name = "Системні вимоги")]
        public string Requirements { get; set; }

        [Display(Name = "Розробник")]
        public virtual Developer Developer { get; set; }
        public virtual ICollection<Purchase> Purchases { get; set; }
    }
}

Databases(C, C#)/DB_lab2/GameStop (Waresoft)/Controllers/DevelopersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Waresoft;

namespace Waresoft.Controllers
{
    public class DevelopersController : Controller
    {
        private const string ERR_DEV_EXISTS = "Введений розробник вже доданий";
        private readonly WaresoftContext _context;

        public DevelopersController(WaresoftContext context)
        {
            _context = context;
        }

        // GET: Developers
        public async Task<IActionResult> Index()
        {
            return View(await _context.Developers.Include("Country").ToListAsync());
        }

        // GET: Developers/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var software = await _context.Software.Where(s => s.DeveloperId == id).Include("Comments").ToListAsync();
            ViewBag.Developer = _context.Developers.Find(id).Name;
            return View();
        }

        // GET: Developers/Create
        public IActionResult Create()
        {
            ViewBag.CountryList = new SelectList(_context.Countries.ToList(), "Id", "Name");
            return View();
        }

        // POST: Developers/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Developer developer)
        {
            bool duplicate = await _context.Developers.AnyAsync(d => d.Name.Equals(developer.Name));

            if (duplicate)
            {
                ModelState.AddModelError("Name", ERR_DEV_EXISTS);
            }

            if (ModelState.IsValid)
            {
                _context.Add(developer);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            ViewBag.CountryList = new SelectList(_context.Countries.ToList(), "Id", "Name");
            return View(developer);
        }

        // GET: Developers/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            var developers = await _context.Developers.FindAsync(id);
            ViewBag.CountryList = new SelectList(_context.Countries.ToList(), "Id", "Name");
            return View(developers);
        }

        // POST: Developers/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Developer developer)
        {
            bool duplicate = await _context.Developers.AnyAsync(d => d.Name.Equals(developer.Name) && d.CountryId == developer.CountryId && d.Id != developer.Id);

            if (duplicate)
            {
                ModelState.AddModelError("Name", ERR_DEV_EXISTS);
            }

            if (ModelState.IsValid)
            {
                _context.Update(developer);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            ViewBag.CountryList = new SelectList(_context.Countries.ToList(), "Id", "Name");
            return View(developer);
        }

        // POST: Developers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var developers = await _context.Developers.FindAsync(id);
            _context.Developers.Remove(developers);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

Databases(C, C#)/DB_lab2/GameStop (Waresoft)/Controllers/PurchasesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Waresoft.Controllers
{
    public class PurchasesController : Controller
    {
        private readonly WaresoftContext _context;

        public PurchasesController(WaresoftContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index(int id)
        {
            List<Purchase> purchases;
            List<Software> software;
            
            ViewBag.CustomerId = id;

            if (id == 0)
            {
                purchases = await _context.Purchases.Include(p => p.Customer).Include(p => p.Software).ToListAsync();
            }
            else
            {
                ViewBag.Customer = _context.Customers.Find(id).Email;
                purchases = await _context.Purchases.Where(p => p.CustomerId == id).Include(p => p.Software).ToListAsync();
            }

            foreach (var p in purchases)
            {
                software = await _context.Software.Where(s => s.Id == p.SoftwareId).Include(s => s.Developer).ToListAsync();
                p.Software = software[0];
            }

            return View(purchases);
        }

        public IActionResult Purchase(int softwareId, int devId)
        {
            FillViewBag(softwareId, devId);
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Purchase(Customer model, int softwareId, int devId)
        {
            var customer = await _context.Customers.FirstOrDefaultAsync(c => c.Email.Equals(model.Email));
            bool duplicate = customer == null ? false : _context.Purchases.Any(p => p.SoftwareId == softwareId && p.CustomerId == customer.Id);

            if (duplicate)
            {
                ModelState.AddModelError("Email", "Ви вже придбали цей продукт");
            }

            if (ModelState.IsValid)
            {                
                if (customer == null)
                {
                    customer = model;
                    await _context.Customers.AddAsync(customer);
                    await _context.SaveChangesAsync();
                }

                var purchase = new Purchase() { CustomerId = customer.Id, SoftwareId = softwareId, Date = DateTime.Now };
                await _context.Purchases.AddAsync(purchase);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Software", new { id = devId, purchased = true });
            }

            FillViewBag(softwareId, devId);
            return View(model);
        }

        public void FillViewBag(int softwareId, int devId)
        {
            ViewBag.DevId = devId;
            ViewBag.SoftwareId = softwareId;
            ViewBag.Software = _context.Software.Find(softwareId).Name;
        }
    }
}

Databases(C, C#)/DB_lab2/GameStop (Waresoft)/Controllers/SoftwareController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Waresoft;

namespace Waresoft.Controllers
{
    public class SoftwareController : Controller
    {
        private const string ERR_SOFT_EXISTS = "Такий продукт вже доданий";
        private readonly WaresoftContext _context;

        public SoftwareController(WaresoftContext context)
        {
            _context = context;
        }

        // GET: Software
        public async Task<IActionResult> Index(int id, bool purchased)
        {
            List<Software> software;
            ViewBag.DevId = id;
            
            if (purchased)
            {
                ViewBag.Purchased = 1;
            }

            if (id == 0)
            {
                software = await _context.Software.Include(s => s.Developer).ToListAsync();
            }
            else
            {
                ViewBag.Developer = _context.Developers.Find(id).Name;
                software = await _context.Software.Where(s => s.DeveloperId == id).Include(s => s.Developer).ToListAsync();
            }

            return View(software);
        }

        // GET: Software/Create
        public IActionResult Create(int devId)
        {
            ViewBag.DevId = devId;
            if (devId != 0)
            {
                ViewBag.Developer = _context.Developers.Find(devId).Name;
            }
            ViewBag.DeveloperList = devId == 0 ?
            new SelectList(_context.Developers, "Id", "Name") :
            new SelectList(new List<Developer>() { _context.Developers.Find(devId) }, "Id", "Name");
            return View();
        }

        // POST: Software/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Software software)
        {
            ViewBag.DevId = software.DeveloperId;
            ViewBag.Developer = _context.Developers.Find(software.DeveloperId).Name;

            bool duplicate = _context.Software.Any(s => s.DeveloperId == software.DeveloperId && s.Name.Equals(software.Name));

            if (duplicate)
            {
                ModelState.AddModelError("Name", ERR_SOFT_EXISTS);
            }

            if (ModelState.IsValid)
            {
                _context.Add(software);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", new { id = software.DeveloperId });
            }

            ViewBag.DeveloperList = new SelectList(_context.Developers, "Id", "Name", software.DeveloperId);
            return View(software);
        }

        // GET: Software/Edit/5
        public async Task<IActionResult> Edit(int id, int devId)
        {
            var software = await _context.Software.FindAsync(id);
            ViewBag.DevId = devId;
            ViewBag.DeveloperList = new SelectList(_context.Developers, "Id", "Name", software.DeveloperId);
            return View(software);
        }

        // POST: Software/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Software software, int devId)
        {
            ViewBag.DevId = devId;
            bool duplicate = _context.Software.Any(s => s.Id != software.Id && s.DeveloperId == software.DeveloperId && s.Name.Equals(software.Name));

            if (duplicate)
            {
                ModelState.AddModelError("Name", ERR_SOFT_EXISTS);
            }

            if (ModelState.IsValid)
            {
                _context.Update(software);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index), new { id = devId });
            }

            ViewBag.DeveloperList = new SelectList(_context.Developers, "Id", "Name", software.DeveloperId);
            return View(software);
        }

        // POST: Software/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var software = await _context.Software.FindAsync(id);
            _context.Software.Remove(software);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

Databases(C, C#)/DB_lab2/GameStop (Waresoft)/Views/Software/Create.cshtml
@model Waresoft.Software

@{
    ViewData["Title"] = "Додати продукт";
}

<h4 id="test">Додати продукт</h4>
<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" novalidate>
            <input type="hidden" name="flag" value="0" />
            <input type="hidden" name="devId" value="@ViewBag.DevId" />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="DeveloperId" class="control-label"></label>
                <select asp-for="DeveloperId" class="form-control" asp-items="@ViewBag.DeveloperList"></select>
            </div>
            <div class="form-group" id="name">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" id="price" maxlength="28" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Requirements" class="control-label"></label>
                <textarea asp-for="Requirements" class="form-control"></textarea>
                <span asp-validation-for="Requirements" class="text-danger"></span>
            </div>
            <table>
                <tr>
                    <td>
                        <input type="submit" value="Додати" class="btn btn-outline-dark" />
                    </td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>
                        <button type="button" class="btn btn-outline-dark" data-toggle="modal" data-target="#confirm">
                            Назад до списку
                        </button>
                    </td>
                </tr>
            </table>
        </form>
    </div>
</div>

<form method="get" asp-action="Index" asp-route-id="@ViewBag.DevId" asp-route-dummy="0">
    <div class="modal fade" id="confirm" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Попередження</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body delete-modal-body">
                    Ви впевнені, що хочете повернутися до списку? Незбережені дані будуть втрачені.
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-outline-dark">Так</button>
                    <button type="button" class="btn btn-outline-dark" data-dismiss="modal">Ні</button>
                </div>
            </div>
        </div>
    </div>
</form>

@section Scripts
{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script>
        $(function () {
            $('#price').keypress(function (e) {
                if (e.target.value === "0" && e.which === 48) {
                    return false;
                }
            });
        });
    </script>
}

Databases(C, C#)/DB_lab2/GameStop (Waresoft)/Views/Software/Edit.cshtml
@model Waresoft.Software

@{
    ViewData["Title"] = "Редагування";
}

<h4>Редагувати дані продукту</h4>
<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" novalidate>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" name="devId" value="@ViewBag.DevId" />
            <div class="form-group">
                <label asp-for="DeveloperId" class="control-label"></label>
                <select asp-for="DeveloperId" class="form-control" asp-items="@ViewBag.DeveloperList"></select>
                <span asp-validation-for="DeveloperId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" id="price" maxlength="28" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Requirements" class="control-label"></label>
                <textarea asp-for="Requirements" class="form-control"></textarea>
                <span asp-validation-for="Requirements" class="text-danger"></span>
            </div>

            <div class="modal fade" id="confirm" tabindex="-1" role="dialog" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title">Попередження</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body delete-modal-body">
                            Ви впевнені, що хочете зберегти внесені зміни?
                        </div>
                        <div class="modal-footer">
                            <button type="submit" class="btn btn-outline-dark" onclick="yes()">Так</button>
                            <button type="button" class="btn btn-outline-dark" data-dismiss="modal">Ні</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

<table>
    <tr>
        <td>
            <button type="button" class="btn btn-outline-dark" data-toggle="modal" data-target="#confirm">
                Зберегти
            </button>
        </td>
        <td></td>
        <td></td>
        <td></td>
        <td>
            <button type="button" class="btn btn-outline-dark" data-toggle="modal" data-target="#confirmBack">
                Назад до списку
            </button>
        </td>
    </tr>
</table>

<form method="get" asp-action="Index" asp-route-id="@ViewBag.DevId">
    <div class="modal fade" id="confirmBack" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Попередження</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body delete-modal-body">
                    Ви впевнені, що хочете повернутися до списку? Незбережені зміни будуть втрачені.
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-outline-dark">Так</button>
                    <button type="button" class="btn btn-outline-dark" data-dismiss="modal">Ні</button>
                </div>
            </div>
        </div>
    </div>
</form>

@section Scripts
{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script>
        function yes() {
            $("#confirm").modal('hide');
        }
    </script>
    <script>
        $(function () {
            $('#price').keypress(function (e) {
                if (e.target.value === "0" && e.which === 48) {
                    return false;
                }
            });
        });
    </script>
}

Databases(C, C#)/DB_lab2/GameStop (Waresoft)/Views/Software/Index.cshtml
@model IEnumerable<Waresoft.Software>

@{
    ViewData["Title"] = "Продукти";
}

@if (ViewBag.DevId == 0)
{
    <h1>Продукти</h1>
}
else
{
    <h1>Продукти @ViewBag.Developer</h1>
}


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Requirements)
            </th>
            @if (ViewBag.DevId == 0)
            {
                <th>
                    @Html.DisplayNameFor(model => model.Developer)
                </th>
            }
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            var targetId = "#modal" + item.Id;
            var modalId = "modal" + item.Id;
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Requirements)
                </td>
                @if (ViewBag.DevId == 0)
                {
                    <td>
                        @Html.DisplayFor(modelItem => item.Developer.Name)
                    </td>
                }
                
                <td>
                    <form method="get" asp-controller="Purchases" asp-action="Purchase">
                        <input type="hidden" name="softwareId" value="@item.Id" />
                        <input type="hidden" name="devId" value="@ViewBag.DevId" />
                        <p>
                            <input type="submit" class="btn btn-outline-dark" value="Придбати" style="width:100px" />
                        </p>
                    </form>
                    <form method="get" asp-action="Edit" asp-route-id="@item.Id">
                        <p>
                            <input type="hidden" name="devId" value="@ViewBag.DevId" />
                            <input type="submit" class="btn btn-outline-dark" value="Редагувати" style="width:100px" />
                        </p>
                    </form>
                    <p>
                        <button type="button" class="btn btn-outline-dark" data-toggle="modal" data-target="@targetId" style="width:100px">
                            Видалити
                        </button>
                    </p>

                    <div class="modal fade" id="@modalId" tabindex="-1" role="dialog" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title">Попередження</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body delete-modal-body">
                                    Ви впевнені, що хочете видалити цей продукт?
                                </div>
                                <div class="modal-footer">
                                    <form asp-action="Delete" asp-route-id="@item.Id">
                                        <button type="submit" class="btn btn-outline-dark">Так</button>
                                        <button type="button" class="btn btn-outline-dark" data-dismiss="modal">Ні</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>

<table>
    <tr>
        <td>
            <form method="get" asp-action="Create">
                <input type="hidden" name="devId" value="@ViewBag.DevId" />
                <input type="submit" class="btn btn-outline-dark" value="Додати новий" />
            </form>
        </td>
        @if (ViewBag.DevId != 0)
        {
            <td></td>
            <td></td>
            <td></td>
            <td>
                <form method="get" asp-controller="Developers" asp-action="Index">
                    <input type="submit" class="btn btn-outline-dark" value="Назад до списку розробників" />
                </form>
            </td>
        }
        <td></td>
        <td></td>
        <td></td>
        <td>
            <form method="get" asp-controller="Home" asp-action="Index">
                <input type="submit" class="btn btn-outline-dark" value="На головну" />
            </form>
        </td>
    </tr>
</table>

<div class="modal fade" id="warning" tabindex="-1" role="alertdialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Повідомлення</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="errorText">
                Дана реалізація програми носить суто демонстраційний характер, тому завантаження реального програмного забезпечення опущено (запис про покупку в базі даних є імітативним). Щоб скористатися послугами розробника, перейдіть на його офіційний сайт.
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline-dark" data-dismiss="modal">ОК</button>
            </div>
        </div>
    </div>
</div>

@section scripts
{
    <script>
        window.addEventListener("load", function () {
            if ('@ViewBag.Purchased' == 1) {
                $("#warning").modal();
            }
        });
    </script>
}