Databases(C, C#)/DB_lab2/GameStop (Waresoft)/Models/Purchases.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Waresoft
{
    public partial class Purchase
    {
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public int SoftwareId { get; set; }

        [Display(Name = "Дата покупки")]
        public DateTime Date { get; set; }

        public virtual Customer Customer { get; set; }
        public virtual Software Software { get; set; }
    }
}

Databases(C, C#)/DB_lab2/GameStop (Waresoft)/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Waresoft;

namespace Waresoft.Controllers
{
    public class CustomersController : Controller
    {
        private readonly WaresoftContext _context;

        public CustomersController(WaresoftContext context)
        {
            _context = context;
        }

        // GET: Customers
        public async Task<IActionResult> Index()
        {
            return View(await _context.Customers.ToListAsync());
        }
    }
}

Databases(C, C#)/DB_lab2/GameStop (Waresoft)/Controllers/PurchasesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Waresoft.Controllers
{
    public class PurchasesController : Controller
    {
        private readonly WaresoftContext _context;

        public PurchasesController(WaresoftContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index(int id)
        {
            List<Purchase> purchases;
            List<Software> software;
            
            ViewBag.CustomerId = id;

            if (id == 0)
            {
                purchases = await _context.Purchases.Include(p => p.Customer).Include(p => p.Software).ToListAsync();
            }
            else
            {
                ViewBag.Customer = _context.Customers.Find(id).Email;
                purchases = await _context.Purchases.Where(p => p.CustomerId == id).Include(p => p.Software).ToListAsync();
            }

            foreach (var p in purchases)
            {
                software = await _context.Software.Where(s => s.Id == p.SoftwareId).Include(s => s.Developer).ToListAsync();
                p.Software = software[0];
            }

            return View(purchases);
        }

        public IActionResult Purchase(int softwareId, int devId)
        {
            FillViewBag(softwareId, devId);
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Purchase(Customer model, int softwareId, int devId)
        {
            var customer = await _context.Customers.FirstOrDefaultAsync(c => c.Email.Equals(model.Email));
            bool duplicate = customer == null ? false : _context.Purchases.Any(p => p.SoftwareId == softwareId && p.CustomerId == customer.Id);

            if (duplicate)
            {
                ModelState.AddModelError("Email", "Ви вже придбали цей продукт");
            }

            if (ModelState.IsValid)
            {                
                if (customer == null)
                {
                    customer = model;
                    await _context.Customers.AddAsync(customer);
                    await _context.SaveChangesAsync();
                }

                var purchase = new Purchase() { CustomerId = customer.Id, SoftwareId = softwareId, Date = DateTime.Now };
                await _context.Purchases.AddAsync(purchase);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Software", new { id = devId, purchased = true });
            }

            FillViewBag(softwareId, devId);
            return View(model);
        }

        public void FillViewBag(int softwareId, int devId)
        {
            ViewBag.DevId = devId;
            ViewBag.SoftwareId = softwareId;
            ViewBag.Software = _context.Software.Find(softwareId).Name;
        }
    }
}

Databases(C, C#)/DB_lab2/GameStop (Waresoft)/Controllers/SoftwareController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Waresoft;

namespace Waresoft.Controllers
{
    public class SoftwareController : Controller
    {
        private const string ERR_SOFT_EXISTS = "Такий продукт вже доданий";
        private readonly WaresoftContext _context;

        public SoftwareController(WaresoftContext context)
        {
            _context = context;
        }

        // GET: Software
        public async Task<IActionResult> Index(int id, bool purchased)
        {
            List<Software> software;
            ViewBag.DevId = id;
            
            if (purchased)
            {
                ViewBag.Purchased = 1;
            }

            if (id == 0)
            {
                software = await _context.Software.Include(s => s.Developer).ToListAsync();
            }
            else
            {
                ViewBag.Developer = _context.Developers.Find(id).Name;
                software = await _context.Software.Where(s => s.DeveloperId == id).Include(s => s.Developer).ToListAsync();
            }

            return View(software);
        }

        // GET: Software/Create
        public IActionResult Create(int devId)
        {
            ViewBag.DevId = devId;
            if (devId != 0)
            {
                ViewBag.Developer = _context.Developers.Find(devId).Name;
            }
            ViewBag.DeveloperList = devId == 0 ?
            new SelectList(_context.Developers, "Id", "Name") :
            new SelectList(new List<Developer>() { _context.Developers.Find(devId) }, "Id", "Name");
            return View();
        }

        // POST: Software/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Software software)
        {
            ViewBag.DevId = software.DeveloperId;
            ViewBag.Developer = _context.Developers.Find(software.DeveloperId).Name;

            bool duplicate = _context.Software.Any(s => s.DeveloperId == software.DeveloperId && s.Name.Equals(software.Name));

            if (duplicate)
            {
                ModelState.AddModelError("Name", ERR_SOFT_EXISTS);
            }

            if (ModelState.IsValid)
            {
                _context.Add(software);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", new { id = software.DeveloperId });
            }

            ViewBag.DeveloperList = new SelectList(_context.Developers, "Id", "Name", software.DeveloperId);
            return View(software);
        }

        // GET: Software/Edit/5
        public async Task<IActionResult> Edit(int id, int devId)
        {
            var software = await _context.Software.FindAsync(id);
            ViewBag.DevId = devId;
            ViewBag.DeveloperList = new SelectList(_context.Developers, "Id", "Name", software.DeveloperId);
            return View(software);
        }

        // POST: Software/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Software software, int devId)
        {
            ViewBag.DevId = devId;
            bool duplicate = _context.Software.Any(s => s.Id != software.Id && s.DeveloperId == software.DeveloperId && s.Name.Equals(software.Name));

            if (duplicate)
            {
                ModelState.AddModelError("Name", ERR_SOFT_EXISTS);
            }

            if (ModelState.IsValid)
            {
                _context.Update(software);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index), new { id = devId });
            }

            ViewBag.DeveloperList = new SelectList(_context.Developers, "Id", "Name", software.DeveloperId);
            return View(software);
        }

        // POST: Software/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var software = await _context.Software.FindAsync(id);
            _context.Software.Remove(software);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

Databases(C, C#)/DB_lab2/GameStop (Waresoft)/Views/Purchases/Index.cshtml
@model IEnumerable<Waresoft.Purchase>

@{
    ViewData["Title"] = "Покупки";
}

@if (ViewBag.CustomerId == 0)
{
    <h1>Покупки</h1>
}
else
{
    <h1>Покупки @ViewBag.Customer</h1>
}

<table class="table">
    <thead>
        <tr>
            @if (ViewBag.CustomerId == 0)
            {
                <th>
                    Email покупця
                </th>
            }
            <th>
                Назва продукту
            </th>
            <th>
                Розробник продукту
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                @if (ViewBag.CustomerId == 0)
                {
                    <td>
                        @Html.DisplayFor(modelItem => item.Customer.Email)
                    </td>
                }
                <td>
                    @Html.DisplayFor(modelItem => item.Software.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Software.Developer.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
            </tr>
        }
    </tbody>
</table>

<table>
    <tr>
        @if (ViewBag.CustomerId != 0)
        {
            <td>
                <form method="get" asp-controller="Customers" asp-action="Index">
                    <input type="submit" class="btn btn-outline-dark" value="Назад до списку покупців" />
                </form>
            </td>
        <td></td>
        <td></td>
        <td></td>
        }
        <td>
            <form method="get" asp-controller="Home" asp-action="Index">
                <input type="submit" class="btn btn-outline-dark" value="На головну" />
            </form>
        </td>
    </tr>
</table>

Databases(C, C#)/DB_lab2/GameStop (Waresoft)/Views/Purchases/Purchase.cshtml
@model Customer

@{
    ViewData["Title"] = "Покупка";
}

<h1>Покупка @ViewBag.Software</h1>
<hr />

<div class="row">
    <div class="col-md-4">
        <form method="post" asp-action="Purchase">
            <input type="hidden" name="softwareId" value="@ViewBag.SoftwareId" />
            <input type="hidden" name="devId" value="@ViewBag.DevId" />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Surname" class="control-label"></label>
                <input asp-for="Surname" class="form-control" />
                <span asp-validation-for="Surname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <table>
                <tr>
                    <td>
                        <input type="submit" value="Придбати" class="btn btn-outline-dark" />
                    </td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>
                        <button type="button" class="btn btn-outline-dark" data-toggle="modal" data-target="#confirm">
                            Назад до списку
                        </button>
                    </td>
                </tr>
            </table>
        </form>
    </div>
</div>

<form method="get" asp-controller="Software" asp-action="Index">
    <input type="hidden" name="id" value="@ViewBag.DevId" />
    <div class="modal fade" id="confirm" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Попередження</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body delete-modal-body">
                    Ви впевнені, що хочете повернутися до списку? Незбережені дані будуть втрачені.
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-outline-dark">Так</button>
                    <button type="button" class="btn btn-outline-dark" data-dismiss="modal">Ні</button>
                </div>
            </div>
        </div>
    </div>
</form>