Databases(C, C#)/DB_lab2/GameStop (Waresoft)/Models/Query.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Waresoft.Models
{
    public class Query
    {
        public string QueryId { get; set; }

        public string Error { get; set; }

        public int ErrorFlag { get; set; }

        public string DevName { get; set; }

        public string CountryName { get; set; }

        public decimal AvgPrice { get; set; }

        public List<string> CustNames { get; set; }

        public List<string> CustSurnames { get; set; }

        public List<string> CustEmails { get; set; }

        public List<string> ProdNames { get; set; }

        public List<decimal> ProdPrices { get; set; }

        public string CustName { get; set; }

        public string CustSurname { get; set; }

        public string CustEmail { get; set; }

        public List<string> DevNames { get; set; }

        public List<DateTime> Dates { get; set; }

        [Required(ErrorMessage = "Поле необхідно заповнити")]
        [RegularExpression(@"^[0-9]+(\.[0-9]{1,2})?$", ErrorMessage = "Введіть коректну вартість")]
        [Display(Name = "Вартість В")]
        public decimal Price { get; set; }

        [Required(ErrorMessage = "Поле необхідно заповнити")]
        [RegularExpression(@"^[0-9]+$", ErrorMessage = "Введіть коректне число")]
        [Display(Name = "Число продуктів N")]
        public decimal Number { get; set; }

        [Required(ErrorMessage = "Поле необхідно заповнити")]
        public string ProdName { get; set; }

        public int DevId { get; set; }

        public List<string> CountryNames { get; set; }
    }
}

Databases(C, C#)/DB_lab2/GameStop (Waresoft)/Controllers/QueriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Npgsql;
using Waresoft.Models;

namespace Waresoft.Controllers
{
    public class QueriesController : Controller
    {
        private const string CONN_STR = "Host=localhost;Port=5432;Database=dblab2;Username=postgres;Password=milkyway12345";
        
        private const string S1_PATH = @"C:\Users\Vlad_2\source\repos\C#\Waresoft(DB Lab2)\Waresoft\Queries\S1.sql";
        private const string S2_PATH = @"C:\Users\Vlad_2\source\repos\C#\Waresoft(DB Lab2)\Waresoft\Queries\S2.sql";
        private const string S3_PATH = @"C:\Users\Vlad_2\source\repos\C#\Waresoft(DB Lab2)\Waresoft\Queries\S3.sql";
        private const string S4_PATH = @"C:\Users\Vlad_2\source\repos\C#\Waresoft(DB Lab2)\Waresoft\Queries\S4.sql";
        private const string S5_PATH = @"C:\Users\Vlad_2\source\repos\C#\Waresoft(DB Lab2)\Waresoft\Queries\S5.sql";
        private const string S6_PATH = @"C:\Users\Vlad_2\source\repos\C#\Waresoft(DB Lab2)\Waresoft\Queries\S6.sql";

        private const string A1_PATH = @"C:\Users\Vlad_2\source\repos\C#\Waresoft(DB Lab2)\Waresoft\Queries\A1.sql";
        private const string A2_PATH = @"C:\Users\Vlad_2\source\repos\C#\Waresoft(DB Lab2)\Waresoft\Queries\A2.sql";
        private const string A3_PATH = @"C:\Users\Vlad_2\source\repos\C#\Waresoft(DB Lab2)\Waresoft\Queries\A3.sql";

        private const string T1_PATH = @"C:\Users\Vlad_2\source\repos\C#\Waresoft(DB Lab2)\Waresoft\Queries\T1.sql";
        private const string T2_PATH = @"C:\Users\Vlad_2\source\repos\C#\Waresoft(DB Lab2)\Waresoft\Queries\T2.sql";

        private const string ERR_AVG = "Неможливо обрахувати середню ціну, оскільки продукти відсутні.";
        private const string ERR_CUST = "Покупці, що задовольняють дану умову, відсутні.";
        private const string ERR_PROD = "Програмні продукти, що задовольняють дану умову, відсутні.";
        private const string ERR_DEV = "Розробники, що задовольняють дану умову, відсутні.";
        private const string ERR_COUNTRY = "Країни, що задовольняють дану умову, відсутні.";
        
        private readonly WaresoftContext _context;

        public QueriesController(WaresoftContext context)
        {
            _context = context;
        }

        public IActionResult Index(int errorCode)
        {
            var customers = _context.Customers.Select(c => c.Name).Distinct().ToList();
            if (errorCode == 1)
            {
                ViewBag.ErrorFlag = 1;
                ViewBag.PriceError = "Введіть коректну вартість";
            }
            if (errorCode == 2)
            {
                ViewBag.ErrorFlag = 2;
                ViewBag.ProdNameError = "Поле необхідно заповнити";
            }
            if (errorCode == 3)
            {
                ViewBag.ErrorFlag = 3;
                ViewBag.NumberError = "Введіть корректне число";
            }

            var empty = new SelectList(new List<string> { "--Пусто--" });
            var anyCusts = _context.Customers.Any();
            var anyDevs = _context.Developers.Any();

            ViewBag.DevIds = anyDevs ? new SelectList(_context.Developers, "Id", "Id") : empty;
            ViewBag.DevNames = anyDevs ? new SelectList(_context.Developers, "Name", "Name") : empty;
            ViewBag.CustNames = anyCusts ? new SelectList(customers) : empty;
            ViewBag.CustEmails = anyCusts ? new SelectList(_context.Customers, "Email", "Email") : empty;
            ViewBag.CustSurnames = anyCusts ? new SelectList(_context.Customers, "Surname", "Surname") : empty;
            ViewBag.Countries = _context.Countries.Any() ? new SelectList(_context.Countries, "Name", "Name") : empty;
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult SimpleQuery1(Query queryModel)
        {
            string query = System.IO.File.ReadAllText(S1_PATH);
            query = query.Replace("P", "N\'" + queryModel.DevName + "\'");
            query = query.Replace("\r\n", " ");
            query = query.Replace('\t', ' ');

            queryModel.QueryId = "S1";

            using (var connection = new NpgsqlConnection(CONN_STR))
            {
                connection.Open();
                using (var command = new NpgsqlCommand(query, connection))
                {
                    var result = command.ExecuteScalar();
                    if (result != DBNull.Value)
                    {
                        queryModel.AvgPrice = Convert.ToDecimal(result);
                    }
                    else
                    {
                        queryModel.ErrorFlag = 1;
                        queryModel.Error = ERR_AVG;
                    }
                }
                connection.Close();
            }
            return RedirectToAction("Result", queryModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult SimpleQuery2(Query queryModel)
        {
            string query = System.IO.File.ReadAllText(S2_PATH);
            query = query.Replace("X", "N\'" + queryModel.DevName + "\'");
            query = query.Replace("\r\n", " ");
            query = query.Replace('\t', ' ');

            queryModel.QueryId = "S2";
            queryModel.CustEmails = new List<string>();

            using (var connection = new NpgsqlConnection(CONN_STR))
            {
                connection.Open();
                using (var command = new NpgsqlCommand(query, connection))
                {
                    command.ExecuteNonQuery();
                    using (var reader = command.ExecuteReader())
                    {
                        int flag = 0;
                        while (reader.Read())
                        {
                            queryModel.CustEmails.Add(reader.GetString(0));
                            flag++;
                        }

                        if (flag == 0)
                        {
                            queryModel.ErrorFlag = 1;
                            queryModel.Error = ERR_CUST;
                        }
                    }
                }
                connection.Close();
            }
            return RedirectToAction("Result", queryModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult SimpleQuery3(Query queryModel)
        {
            string query = System.IO.File.ReadAllText(S3_PATH);
            query = query.Replace("K", "N\'" + queryModel.CountryName + "\'");
            query = query.Replace("\r\n", " ");
            query = query.Replace('\t', ' ');

            queryModel.QueryId = "S3";
            queryModel.DevNames= new List<string>();

            using (var connection = new NpgsqlConnection(CONN_STR))
            {
                connection.Open();
                using (var command = new NpgsqlCommand(query, connection))
                {
                    command.ExecuteNonQuery();
                    using (var reader = command.ExecuteReader())
                    {
                        int flag = 0;
                        while (reader.Read())
                        {
                            queryModel.DevNames.Add(reader.GetString(0));
                            flag++;
                        }

                        if (flag == 0)
                        {
                            queryModel.ErrorFlag = 1;
                            queryModel.Error = ERR_DEV;
                        }
                    }
                }
                connection.Close();
            }
            return RedirectToAction("Result", queryModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult SimpleQuery4(Query queryModel)
        {
            string query = System.IO.File.ReadAllText(S4_PATH);
            query = query.Replace("X", "N\'" + queryModel.CustName + "\'");
            query = query.Replace("Y", "N\'" + queryModel.CustSurname + "\'");
            query = query.Replace("Z", "N\'" + queryModel.CustEmail + "\'");
            query = query.Replace("\r\n", " ");
            query = query.Replace('\t', ' ');

            queryModel.QueryId = "S4";
            queryModel.DevNames = new List<string>();

            using (var connection = new NpgsqlConnection(CONN_STR))
            {
                connection.Open();
                using (var command = new NpgsqlCommand(query, connection))
                {
                    command.ExecuteNonQuery();
                    using (var reader = command.ExecuteReader())
                    {
                        int flag = 0;
                        while (reader.Read())
                        {
                            queryModel.DevNames.Add(reader.GetString(0));
                            flag++;
                        }

                        if (flag == 0)
                        {
                            queryModel.ErrorFlag = 1;
                            queryModel.Error = ERR_DEV;
                        }
                    }
                }
                connection.Close();
            }
            return RedirectToAction("Result", queryModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult SimpleQuery5(Query queryModel)
        {
            if (ModelState["Price"].Errors.Count == 0 && ModelState["Number"].Errors.Count == 0)
            {
                string query = System.IO.File.ReadAllText(S5_PATH);

Databases(C, C#)/DB_lab2/GameStop (Waresoft)/Views/Queries/Index.cshtml
@model Query

@{
    ViewData["Title"] = "Запити";
}

<h1>Запити</h1>
<hr />

<h3>Прості</h3>
<hr />

<p style="font-size:20px">
    <b>Запит 1</b>
</p>
<p style="font-size:17px">
    Знайти максимальну вартість програмних продуктів розробника P.
</p>
<div class="row">
    <div class="col-md-4">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <form asp-action="SimpleQuery1">
            <input type="hidden" asp-for="ProdName" value="dummy" />
            <input type="hidden" asp-for="Price" value="0" />
            <div class="form-group">
                <label class="control-label">Ім'я розробника Р</label>
                <select asp-for="DevName" asp-items="@ViewBag.DevNames" class="form-control"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Надіслати" class="btn btn-outline-dark" />
            </div>
        </form>
    </div>
</div>
<hr />

<p style="font-size:20px">
    <b>Запит 2</b>
</p>
<p style="font-size:17px">
    Знайти email-и покупців, що придбали хоча б один програмний продукт розробника Р та мають ім'я Vlad.
</p>
<div class="row">
    <div class="col-md-4">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <form asp-action="SimpleQuery2">
            <input type="hidden" asp-for="ProdName" value="dummy" />
            <input type="hidden" asp-for="Price" value="0" />
            <div class="form-group">
                <label class="control-label">Ім'я розробника Р</label>
                <select asp-for="DevName" asp-items="@ViewBag.DevNames" class="form-control"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Надіслати" class="btn btn-outline-dark" />
            </div>
        </form>
    </div>
</div>
<hr />

<p style="font-size:20px">
    <b>Запит 3</b>
</p>
<p style="font-size:17px">
    Знайти усіх імена розробників із країни К.
</p>
<div class="row">
    <div class="col-md-4">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <form asp-action="SimpleQuery3">
            <input type="hidden" asp-for="ProdName" value="dummy" />
            <input type="hidden" asp-for="Price" value="0" />
            <div class="form-group">
                <label class="control-label">Назва країни К</label>
                <select asp-for="CountryName" asp-items="@ViewBag.Countries" class="form-control"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Надіслати" class="btn btn-outline-dark" />
            </div>
        </form>
    </div>
</div>
<hr />

<p style="font-size:20px">
    <b>Запит 4</b>
</p>
<p style="font-size:17px">
    Знайти країни, з яких походять розробники усіх програмних продуктів, придбаних покупцем з іменем І, прізвищем П та email-ом Е.
</p>
<div class="row">
    <div class="col-md-4">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <form asp-action="SimpleQuery4">
            <input type="hidden" asp-for="ProdName" value="dummy" />
            <input type="hidden" asp-for="Price" value="0" />
            <div class="form-group">
                <label class="control-label">Ім'я покупця І</label>
                <select id="q4" asp-for="CustName" asp-items="@ViewBag.CustNames" class="form-control"></select>
            </div>
            <div class="form-group">
                <label class="control-label">Прізвище покупця П</label>
                <select asp-for="CustSurname" asp-items="@ViewBag.CustSurnames" class="form-control"></select>
            </div>
            <div class="form-group">
                <label class="control-label">Email покупця Е</label>
                <select asp-for="CustEmail" asp-items="@ViewBag.CustEmails" class="form-control"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Надіслати" class="btn btn-outline-dark" />
            </div>
        </form>
    </div>
</div>
<hr />

<p style="font-size:20px">
    <b id="q5">Запит 5</b>
</p>
<p style="font-size:17px">
    Знайти імена розробників, які продають продукти вартістю більше В у.о. та мають більше ніж N продуктів
</p>
<div class="row">
    <div class="col-md-4">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <form asp-action="SimpleQuery5">
            <input type="hidden" asp-for="ProdName" value="dummy" />
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input maxlength="28" id="price" asp-for="Price" class="form-control" />
                <span class="text-danger">@ViewBag.PriceError</span>
            </div>
            <div class="form-group">
                <label asp-for="Number" class="control-label"></label>
                <input maxlength="28" id="number" asp-for="Number" class="form-control" />
                <span class="text-danger">@ViewBag.NumberError</span>
            </div>
            <div class="form-group">
                <input type="submit" value="Надіслати" class="btn btn-outline-dark" onclick="submit5()" />
            </div>
        </form>
    </div>
</div>
<hr />

<p style="font-size:20px">
    <b>Запит 6</b>
</p>
<p style="font-size:17px">
    Знайти дати покупок продуктів не з назвою Н.
</p>
<div class="row">
    <div class="col-md-4">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <form asp-action="SimpleQuery6">
            <input type="hidden" asp-for="Price" value="0" />
            <div class="form-group">
                <label class="control-label">Назва Н</label>
                <input maxlength="50" asp-for="ProdName" class="form-control" id="prodName" />
                <span class="text-danger">@ViewBag.ProdNameError</span>
            </div>
            <div class="form-group">
                <input type="submit" value="Надіслати" class="btn btn-outline-dark" />
            </div>
        </form>
    </div>
</div>
<hr />

<h3>Множинні</h3>
<hr />

<p style="font-size:20px">
    <b>Запит 1</b>
</p>
<p style="font-size:17px">
    Знайти ті програмні продукти, розробники яких продають принаймні ті ж програмні продукти, що й розробник із кодом Q.
</p>
<div class="row">
    <div class="col-md-4">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <form asp-action="AdvancedQuery1">
            <input type="hidden" asp-for="ProdName" value="dummy" />
            <input type="hidden" asp-for="Price" value="0" />
            <div class="form-group">
                <label class="control-label">Код розробника К</label>
                <select asp-for="DevId" asp-items="@ViewBag.DevIds" class="form-control"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Надіслати" class="btn btn-outline-dark" />
            </div>
        </form>
    </div>
</div>
<hr />

<p style="font-size:20px">
    <b>Запит 2</b>
</p>
<p style="font-size:17px">
    Знайти email-и покупців, які придбали точно ті ж самі програмні продукти, що й покупець з email E.
</p>
<div class="row">
    <div class="col-md-4">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <form asp-action="AdvancedQuery2">
            <input type="hidden" asp-for="ProdName" value="dummy" />
            <input type="hidden" asp-for="Price" value="0" />
            <div class="form-group">
                <label class="control-label">Email E</label>
                <select asp-for="CustEmail" asp-items="@ViewBag.CustEmails" class="form-control"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Надіслати" class="btn btn-outline-dark" />
            </div>
        </form>
    </div>
</div>
<hr />

<p style="font-size:20px">
    <b>Запит 3</b>
</p>
<p style="font-size:17px">
    Знайти прізвища та email-и покупців з іменем І, які придбали всі наявні програмні продукти.
</p>
<div class="row">
    <div class="col-md-4">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <form asp-action="AdvancedQuery3">
            <input type="hidden" asp-for="ProdName" value="dummy" />
            <input type="hidden" asp-for="Price" value="0" />
            <div class="form-group">
                <label class="control-label">Ім'я І</label>
                <select asp-for="CustName" asp-items="@ViewBag.CustNames" class="form-control"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Надіслати" class="btn btn-outline-dark" />
            </div>
        </form>
    </div>
</div>
<hr />

<div class="container" style="display:none">
    <h3>Запити від викладача</h3>
    <hr />

    <p style="font-size:20px;">
        <b>Запит 1</b>
    </p>
    <p style="font-size:17px">
        Знайти ..
    </p>
    <div class="row">
        <div class="col-md-4">
            <form asp-action="TeacherQuery1">
                <input type="hidden" asp-for="ProdName" value="dummy" />
                <input type="hidden" asp-for="Price" value="0" />
                <div class="form-group">

                </div>
                <div class="form-group">
                    <input type="submit" value="Надіслати" class="btn btn-outline-dark" />
                </div>
            </form>
        </div>
    </div>
    <hr />

    <p style="font-size:20px;">
        <b>Запит 2</b>
    </p>
    <p style="font-size:17px">
        Знайти ..
    </p>
    <div class="row">
        <div class="col-md-4">
            <form asp-action="TeacherQuery2">
                <input type="hidden" asp-for="ProdName" value="dummy" />
                <input type="hidden" asp-for="Price" value="0" />
                <div class="form-group">

                </div>
                <div class="form-group">
                    <input type="submit" value="Надіслати" class="btn btn-outline-dark" />
                </div>
            </form>
        </div>
    </div>
    <hr />
</div>


<form method="get" asp-controller="Home" asp-action="Index">
    <input type="submit" class="btn btn-outline-dark" value="На головну" />
</form>

@section scripts
{
    <script>
        window.addEventListener("load", function () {
            if ('@ViewBag.ErrorFlag' == 2) {
                document.getElementById("q4").scrollIntoView();
            }
            else if ('@ViewBag.ErrorFlag' == 1 || '@ViewBag.ErrorFlag' == 3) {
                document.getElementById("q5").scrollIntoView();
            }
        });
    </script>
}

Databases(C, C#)/DB_lab2/GameStop (Waresoft)/Views/Queries/Result.cshtml
@model Query

@{
    ViewData["Title"] = "Результат";
}

<h1>Результат</h1>
<hr />

@if (string.IsNullOrEmpty(Model.Error))
{
    @if (Model.QueryId.Equals("S1"))
    {
        <p style="font-size:20px">
            <b>Максимальна ціна продуктів розробника @Model.DevName:</b> @decimal.Round(Model.AvgPrice, 2, MidpointRounding.AwayFromZero)
        </p>
    }
    else if (Model.QueryId.Equals("S2"))
    {
        <p style="font-size:20px">
            <b>Email-и покупців на ім'я Vlad, що придбали хоча б один продукт розробника @Model.DevName</b>
        </p>
        <table class="table">
            <thead>
                <tr>
                    <th>
                        Email
                    </th>
                </tr>
            </thead>
            <tbody>
                @for (int i = 0; i < Model.CustEmails.Count; i++)
                {
                    <tr>
                        <td>
                            @Model.CustEmails[i]
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else if (Model.QueryId.Equals("S3"))
    {
        <p style="font-size:20px">
            <b>Імена усіх розробників із країни @Model.CountryName</b>
        </p>
        <table class="table">
            <thead>
                <tr>
                    <th>
                        Name
                    </th>
                </tr>
            </thead>
            <tbody>
                @for (int i = 0; i < Model.DevNames.Count; i++)
                {
                    <tr>
                        <td>
                            @Model.DevNames[i]
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else if (Model.QueryId.Equals("S4"))
    {
        <p style="font-size:20px">
            <b>Країни, з яких походять розробники усіх програмних продуктів, придбаних покупцем з ім'ям @Model.CustName, прізвищем @Model.CustSurname та email-ом @Model.CustEmail</b>
        </p>
        <table class="table">
            <thead>
                <tr>
                    <th>
                        Ім'я/назва
                    </th>
                </tr>
            </thead>
            <tbody>
                @for (int i = 0; i < Model.DevNames.Count; i++)
                {
                    <tr>
                        <td>
                            @Model.DevNames[i]
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else if (Model.QueryId.Equals("S5"))
    {
        <p style="font-size:20px">
            <b>Імена розробників, які продають продукти ціною більше @Model.Price у.о. та мають більше @Model.Number продуктів</b>
        </p>
        <table class="table">
            <thead>
                <tr>
                    <th>
                        Ім'я/назва
                    </th>
                </tr>
            </thead>
            <tbody>
                @for (int i = 0; i < Model.DevNames.Count; i++)
                {
                    <tr>
                        <td>
                            @Model.DevNames[i]
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else if (Model.QueryId.Equals("S6"))
    {
        <p style="font-size:20px">
            <b>Дати покупок продуктів не з назвою @Model.ProdName</b>
        </p>
        <table class="table">
            <thead>
                <tr>
                    <th>
                        Дата
                    </th>
                </tr>
            </thead>
            <tbody>
                @for (int i = 0; i < Model.Dates.Count; i++)
                {
                    <tr>
                        <td>
                            @Model.Dates[i]
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else if (Model.QueryId.Equals("A1"))
    {
        <p style="font-size:20px">
            <b>Програмні продукти, розробники яких продають принаймні ті ж програмні продукти, що й розробник із кодом @Model.DevId</b>
        </p>
        <table class="table">
            <thead>
                <tr>
                    <th>
                        Назва
                    </th>
                </tr>
            </thead>
            <tbody>
                @for (int i = 0; i < Model.ProdNames.Count; i++)
                {
                    <tr>
                        <td>
                            @Model.ProdNames[i]
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else if (Model.QueryId.Equals("A2"))
    {
        <p style="font-size:20px">
            <b>Email-и покупців, які придбали точно ті ж самі програмні продукти, що й покупець з email @Model.CustEmail</b>
        </p>
        <table class="table">
            <thead>
                <tr>
                    <th>
                        Emails
                    </th>
                </tr>
            </thead>
            <tbody>
                @for (int i = 0; i < Model.CustEmails.Count; i++)
                {
                    <tr>
                        <td>
                            @Model.CustEmails[i]
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else if (Model.QueryId.Equals("A3"))
    {
        <p style="font-size:20px">
            <b>Прізвища та email-и покупців з іменем @Model.CustName, які придбали всі наявні програмні продукти</b>
        </p>
        <table class="table">
            <thead>
                <tr>
                    <th>
                        Прізвище
                    </th>
                    <th>
                        Email
                    </th>
                </tr>
            </thead>
            <tbody>
                @for (int i = 0; i < Model.CustSurnames.Count; i++)
                {
                    <tr>
                        <td>
                            @Model.CustSurnames[i]
                        </td>
                        <td>
                            @Model.CustEmails[i]
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else if (Model.QueryId.Equals("T1"))
    {

    }
    else if (Model.QueryId.Equals("T2"))
    {

    }
}
else
{
    <p style="font-size:20px">
        Результат запиту порожній.
        <br />
        Будь ласка, спробуйте ще раз з іншим параметром.
    </p>
}

<table>
    <tr>
        <td>
            <form method="get" asp-controller="Queries" asp-action="Index">
                <input type="submit" class="btn btn-outline-dark" value="Назад до запитів" />
            </form>
        </td>
        <td></td>
        <td></td>
        <td></td>
        <td>
            <form method="get" asp-controller="Home" asp-action="Index">
                <input type="submit" class="btn btn-outline-dark" value="На головну" />
            </form>
        </td>
    </tr>
</table>


<div class="modal fade" id="error" tabindex="-1" role="alertdialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Повідомлення</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="errorText">
                @Model.Error
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline-dark" data-dismiss="modal">ОК</button>
            </div>
        </div>
    </div>
</div>

@section scripts
{
    <script>
        window.addEventListener("load", function () {
            if ('@Model.ErrorFlag' == 1) {
                $("#error").modal();
            }
        });
    </script>
}